name: Pull application.yml

on:
  push:
    branches:
      - develop  # 원하는 브랜치로 변경 가능

jobs:
  pull-application-yml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull application.yml from develop
        run: |
          git fetch origin develop
          git checkout origin/develop -- application.yml
      - name: Set TEST_KEY in application.yml
        env:
          TEST_KEY: ${{ secrets.TEST_KEY }}
        run: |
          sed -i "s#test-key-placeholder#$TEST_KEY#g" application.yml
          git add application.yml
          git commit -m "Update application.yml with TEST_KEY"
          git push origin develop  # 또는 원하는 브랜치로 변경 가능
