name: Download application-secret.yml

on:
  push:
    branches:
      - develop

jobs:
  download-secret:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Download application-secret.yml
      env:
        OCCUPY_SECRET: ${{ secrets.TEST_YML }}  # GitHub Secrets에 저장된 값
      run: echo $OCCUPY_SECRET | base64 --decode
      id: get_secret

    - name: Save to local file
      env:
        SECRET_PATH: testActions/src/main/resources/application-secret.yml  # 로컬에 저장할 경로
      run: echo "${{ steps.get_secret.outputs.stdout }}" > $SECRET_PATH
