name: Download application-secret.yml

on:
  push:
    branches:
      - develop

jobs:
  download-secret:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Download application-secret.yml
      env:
        SECRET_PATH: testActions/src/main/resources/application-secret.yml  # 로컬에 저장할 경로
        OCCUPY_SECRET: ${{ secrets.TEST_YML }}  # GitHub Secrets에 저장된 값
      run: |
        echo $OCCUPY_SECRET | base64 --decode > $SECRET_PATH

    - name: Save to GitHub Actions artifact
      uses: actions/upload-artifact@v2
      with:
        name: application-secret
        path: testActions/src/main/resources/application-secret.yml
