name: Pull and update application.yml

on:
  push:
    branches:
      - develop  # 원하는 브랜치로 변경 가능

jobs:
  pull-and-update-application-yml:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Print GitHub workspace
      run: echo "GitHub workspace is $GITHUB_WORKSPACE"

    - name: Find application.yml
      run: |
        find $GITHUB_WORKSPACE -name "application.yml" -type f

    
      
    
