name: Pull and update application.yml

on:
  push:
    branches:
      - develop  # 원하는 브랜치로 변경 가능

jobs:
  pull-and-update-application-yml:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Print GitHub workspace
      run: echo "GitHub workspace is $GITHUB_WORKSPACE"
           echo "{path}" >> $GITHUB_PATH

    - name: Find application.yml
      run: |
        APPLICATION_YML_PATH=$(find $GITHUB_WORKSPACE -name "application.yml" -type f)
        echo "Found application.yml at $APPLICATION_YML_PATH"

    - name: Copy Secret
      env:
        OCCUPY_SECRET: ${{ secrets.TEST_YML }}
      run: |
        OCCUPY_SECRET_DIR= testActions/src/main/resources
        OCCUPY_SECRET_TEST_DIR= testActions/src/test/resources
        OCCUPY_SECRET_DIR_FILE_NAME: application-secret.yml

        echo $OCCUPY_SECRET | base64 --decode > $OCCUPY_SECRET_DIR/$OCCUPY_SECRET_DIR_FILE_NAME
        echo $OCCUPY_SECRET | base64 --decode > $OCCUPY_SECRET_TEST_DIR/$OCCUPY_SECRET_DIR_FILE_NAME
