name: Pull and update application.yml

on:
  push:
    branches:
      - develop  # 원하는 브랜치로 변경 가능

jobs:
  pull-and-update-application-yml:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Download application-secret.yml
      env:
        SECRET_PATH: Actions/src/main/resources/application-secret.yml  # 로컬에 저장할 경로
        OCCUPY_SECRET: ${{ secrets.TEST_YML }}  # GitHub Secrets에 저장된 값
      run: |
        echo $OCCUPY_SECRET | base64 --decode > $SECRET_PATH
