name: Download application-secret.yml

on:
  push:
    branches:
      - develop

jobs:
  download-secret:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      run: git clone https://github.com/ovo1234/testAction.git

    - name: Download yml
      env:
        SECRET_PATH: ./application-secret.yml  # 로컬에 저장할 경로
        OCCUPY_SECRET: ${{ secrets.TEST_YML }}  # GitHub Secrets에 저장된 값
        GITHUB_TOKEN: ${{ secrets.TOKEN_KEY }}  # GitHub의 토큰
      run: |
        echo $OCCUPY_SECRET | base64 --decode > $SECRET_PATH

        # GitHub API를 이용하여 아티팩트 업로드
        curl -H "Authorization: token $GITHUB_TOKEN" \
             -H "Accept: application/vnd.github.v3+json" \
             -H "Content-Type: application/zip" \
             --data-binary @$SECRET_PATH \
             "https://api.github.com/repos/ovo1234/testAction/actions/artifacts"

    - name: Clean up
      run: rm ./application-secret.yml
